In [2]:
import numpy as np

Create a NumPy Array

In [3]:
np.array([1, 2, 3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create Array of Zeros

In [ ]:
np.zeros((1, 10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Create Array of Ones

In [9]:
np.ones((1, 10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Create Even Numbers Array

In [11]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

Create a 3×3 Matrix

In [12]:
np.array([[1, 2, 3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Find Shape of Array

In [13]:
np.shape(np.array([[1, 2, 3],[4,5,6],[7,8,9]]))

(3, 3)

Reshape an Array

In [21]:
mylist =np.array([1, 2, 3,5,6,7,8,9,10,11,12,13])
print(mylist)

[ 1  2  3  5  6  7  8  9 10 11 12 13]


In [23]:
resh=mylist.reshape(3,4)
print(resh)

[[ 1  2  3  5]
 [ 6  7  8  9]
 [10 11 12 13]]


Generate Random Numbers

In [27]:
arr=np.random.randint(5)
print(arr)

1


Find Maximum and Minimum

In [29]:
print(min(mylist))
print(max(mylist))

1
13


Array Addition

In [31]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


Multiply Array by Scalar

In [32]:
ar=np.array([1, 2, 3])
print(ar*5)

[ 5 10 15]


Create Identity Matrix

In [33]:
matrix=np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Find Mean

In [34]:
np.average(mylist)

7.25

Indexing in NumPy

In [35]:
a=np.array([1, 2, 3, 4, 5, 6, 7])
print(a[2:6])

[3 4 5 6]
